### PR TITLE
fix(reducer/change): allow `change` to handle `undefined` payload

### LINKED ISSUE #3946: Calling Field's input.onChange(undefined) does not set field value to undefined.
Hey there, 
I'm trying to reset a form field to be `undefined` but it doesn't seem to work. Here is a codesandbox showing it not working: 

https://codesandbox.io/s/5w72x5rpmx

It does work passing `null`, but I am confused why `undefined` doesn't work. I couldn't find any mention of why this would be the case in the docs but maybe I missed something. 

Besides this behavior being confusing, I would especially love it to be set to `undefined` (and not `null` or `false`) in my case because I often set certain default values for my form values using the 
```
const {input: {value = "hey"}} = this.props
```
Which only works if the value gets reset to `undefined`.

Thanks!

### PR DESCRIPTION
**Pull request by tnrich**
Closes #3946

### CODE REVIEW

**Comment by iamandrewluca** [comment]
Tests fail.

File: src/createReducer.js [hunk 1]
```diff
@@ -303,7 +303,7 @@ function createReducer<M, L>(structure: Structure<M, L>) {
     ) {
       let result = state
       const initial = getIn(result, `initial.${field}`)
-      if (initial === undefined && payload === '') {
+      if (payload === '') {
```
Comment (iamandrewluca) [inline src/createReducer.js]: to not make this a breaking change for thoose who use `''` to reset value use bellow suggestion
```suggestion
      if ((initial === undefined && payload === '') || payload === undefined) {
```

Comment (iamandrewluca) [reply src/createReducer.js]: this will break only 2 tests, fix them to allow `undefined` value
```
  ● reducer.immutable › reducer.immutable.change › should allow setting an initialized field to ''
  ● reducer.immutable › reducer.immutable.change › should not modify a value if called with undefined
```

Comment (iamandrewluca) [reply src/createReducer.js]: this should be `request change`

Comment (iamandrewluca) [inline src/createReducer.js]: to not make this a breaking change for thoose who use `''` to reset value use bellow suggestion
```suggestion
      if ((initial === undefined && payload === '') || payload === undefined) {
```

this will break only 2 tests, fix them to allow `undefined` value

```
  ● reducer.immutable › reducer.immutable.change › should allow setting an initialized field to ''
  ● reducer.immutable › reducer.immutable.change › should not modify a value if called with undefined
```

Comment (iamandrewluca) [reply src/createReducer.js]: I think only `reset` should reset to `initialValue`, using `change` should allow any value to be changed

Comment (iamandrewluca) [reply src/createReducer.js]: https://github.com/erikras/redux-form/blob/c89ee4473bc497f2740bc742df9e30b7263419d7/src/__tests__/helpers/reducer.change.js#L189
remove `values` and tests should work.

Comment (iamandrewluca) [reply src/createReducer.js]: https://github.com/erikras/redux-form/blob/c89ee4473bc497f2740bc742df9e30b7263419d7/src/__tests__/helpers/reducer.change.js#L189
remove `values` and tests should work

Comment (iamandrewluca) [inline src/createReducer.js]: to not make this a breaking change for thoose who use `''` to reset value use bellow suggestion
```suggestion
      if ((initial === undefined && payload === '') || payload === undefined) {
```

this will break only 2 tests, fix them to allow `undefined` value

```
  ● reducer.immutable › reducer.immutable.change › should allow setting an initialized field to ''
  ● reducer.immutable › reducer.immutable.change › should not modify a value if called with undefined
```

I think only `reset` should reset to `initialValue`, using `change` should allow any value to be changed. But this will be a breaking change

https://github.com/erikras/redux-form/blob/c89ee4473bc497f2740bc742df9e30b7263419d7/src/__tests__/helpers/reducer.change.js#L189
remove `values` and tests should work

**Comment by tnrich** [comment]
@iamandrewluca I tried to make the changes but I'm not sure if I got them all. Could you let me know if I need to make anymore?

**Comment by tnrich** [comment]
Also, @iamandrewluca it looks like the tests are failing for an unrelated error: 

```
    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [Error: Fields must be inside a component decorated with reduxForm()]
```

Maybe I need to merge in the latest commits on master?

File: src/__tests__/helpers/reducer.change.js [hunk 2]
```diff
@@ -187,7 +187,6 @@ const describeChange = (reducer, expect, { fromJS }) => () => {
       foo: {
         anyTouched: true,
         values: {
```
Comment (iamandrewluca) [inline src/__tests__/helpers/reducer.change.js]: in reducer is used function `deleteInWithCleanUp` to cleanup, from it tests I see that if an object has no children it also removes the parent. In this case you should also remove `values` object
```suggestion
```

File: src/__tests__/helpers/reducer.change.js [hunk 3]
```diff
@@ -187,7 +187,6 @@ const describeChange = (reducer, expect, { fromJS }) => () => {
...
-          myField: 'initialValue'
         },
```
Comment (iamandrewluca) [inline src/__tests__/helpers/reducer.change.js]:
```suggestion
```

**Comment by iamandrewluca** [comment]
@tnrich those are just `console.error` from code, they are expected. I think we should run tests in silent mode to have a more cleaner output.

**Comment by tnrich** [comment]
Okay awesome I applied your suggestions. Thanks! Is it all ready to go now?

**Comment by iamandrewluca** [comment]
@tnrich yeap, we just need to wait for an project collaborator :)

**Comment by tnrich** [comment]
Perfect thanks so much! I hope it'll go through!

**Comment by iamandrewluca** [comment]
Would be great to have title more descriptive, may catch collaborators eyes
```
feat(reducer/change): allow `change` to handle `undefined` value
```
and include in body
```
Closes #3946
```

**Comment by iamandrewluca** [comment]
Also I would opt to deprecate using this `initial === undefined && payload === ''` in `change`.  
This allows only to clean field when initial value is undefined.
User should take care to what value is changing.

**Comment by tnrich** [comment]
> Also I would opt to deprecate using this initial === undefined && payload === '' in change.
This allows only to clean field when initial value is undefined.
User should take care to what value is changing.

How should I go about doing that? @iamandrewluca

**Comment by iamandrewluca** [comment]
Wi'll think of that in a future refactor.

**Comment by renatoagds** [comment]
Published in [`v8.2.6`](https://github.com/erikras/redux-form/releases/tag/v8.2.6).
