### PR TITLE
Fix #2718 (Incorrect way of accessing syncErrors, syncWarnings in ConnectedField, ConnectedFieldArray, ConnectedFields for redux-form/immutable)

### LINKED ISSUE #2718: Incorrect way of accessing syncErrors, syncWarnings in ConnectedField, ConnectedFieldArray, ConnectedFields for redux-form/immutable
**bug report**

### What is the current behavior?

1. Create simple field with _Field-level validator_ using `redux-form/immutable`.

```
import { Field } from 'redux-form/immutable';

const required = value => (value ? undefined : 'Required');
const renderField = ({ input, type, meta: { error } }) => {
  return (
    <div>
      <div>
        <input {...input} type={type} />
        {error && <span>{error}</span>}
      </div>
    </div>
  );
};

<Field name="username" type="text" component={renderField} validate={required} />
```

2. Type something
3. Remove content from input
4. `@@redux-form/UPDATE_SYNC_ERRORS` event appears with `syncErrors: {username:'Required'}` payload
5. **No error message is visible**

### What is the expected behavior?
`Required` string is assigned to `meta.error` variable.

Currently `error` is `undefined`.

### What's your environment?
`redux-form: 6.5.0`

### Other informations
In `ConnectedField.js` during the `getSyncError` call, `syncErrors` contains valid `{username:'Required'}` object as an `Immutable.Map`

### What's your environment?
`redux-form: 6.5.0`

### Other informations
In `ConnectedField.js` during the `getSyncError` call, `syncErrors` contains `{username:'Required'}` **Immutable.Map* object.

Meanwhile in https://github.com/erikras/redux-form/blob/master/src/ConnectedField.js#L15 you are extracting error using `plain.getIn(syncErrors, name)` instead of `getIn(syncErrors, name)`

The same issue occurs for `syncWarnings` in all of `ConnectedField*` files:

- `ConnectedField.js`
- `ConnectedFieldArray.js`
- `ConnectedFields.js`

This breaks validation in general when using immutable.

### PR DESCRIPTION
**Pull request by hsz**
Use `getIn` instead of `plain.getIn` in case we're using `redux-form/immutable`.

Ref. https://github.com/erikras/redux-form/issues/2718

### CODE REVIEW

File: src/ConnectedFields.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ const createConnectedFields = ({ deepEqual, getIn, toJS, size }) => {
         }, {})
       }
     }
-
```
Comment (hsz) [inline src/ConnectedFields.js]: Just extra whitespaces removed from the end of the line by the IDE.

File: src/ConnectedFields.js [hunk 2]
```diff
@@ -159,7 +159,7 @@ const createConnectedFields = ({ deepEqual, getIn, toJS, size }) => {
       return {
         _fields: names.reduce((accumulator, name) => {
           const initialState = getIn(formState, `initial.${name}`)
-          const initial = initialState !== undefined ? initialState : (initialValues && getIn(initialValues, name))
```
Comment (hsz) [inline src/ConnectedFields.js]: Just extra whitespaces removed from the end of the line by the IDE.

**Comment by erikras** [comment]
Nice work. This was vestigial from before we put the sync errors into the Redux state, and we allowed the validation function to return a regular object, even if you were using immutable.

**Comment by hsz** [comment]
@erikras Thanks. And here comes the question - when do you plan to do the next release? I've migrated our product from 2.x to the current redux-form version, but the validation case is the latest one that blocks us from going live. I've tested this fix and previous validators work out of the box.

**Comment by erikras** [comment]
Published in [`v6.6.0`](https://github.com/erikras/redux-form/releases/tag/v6.6.0).
